# Get OS

FROM node:16-alpine

# define work dir. If not exist it will cretae one

WORKDIR /usr/app
# install dependencies

COPY ./package.json ./

RUN npm install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY ./ ./

# run command

CMD ["npm", "run", "start"]